ARG DOCKER_REGISTRY
FROM ${DOCKER_REGISTRY}/duckietown/challenge-aido_lf-experiment_manager:daffy-amd64

ARG SCENARIOS

RUN echo scenarios ${SCENARIOS}
COPY ${SCENARIOS} /scenarios
RUN find /scenarios
