ARG DOCKER_REGISTRY=docker.io
FROM ${DOCKER_REGISTRY}/duckietown/dt-gui-tools:daffy-amd64

RUN pip3 install -U \
    aido-protocols-daffy

COPY assets/vnc/image/root/Desktop/. /root/Desktop/
COPY assets/vnc/image/root/Documents/. /root/Documents/

COPY assets/vnc/image/root/icons/. /root/.icons/
COPY assets/vnc/image/usr/bin/. /usr/bin/
COPY assets/vnc/image/opt/ros/noetic/share/rviz/. /opt/ros/noetic/share/rviz/

RUN rm /root/Desktop/intrinsic_calibration.desktop

CMD ["dt-launcher-jupyter"]
