
ARG DOCKER_REGISTRY=docker.io
FROM ${DOCKER_REGISTRY}/duckietown/dt-gui-tools:daffy-amd64

RUN /usr/bin/python3 -m pip install --upgrade pip

RUN pip3 install -U \
    aido-protocols-daffy \
    duckietown-world-daffy \
    tqdm \
    ipywidgets



RUN apt update && apt install unzip

#COPY requirements.txt requirements.txt
#RUN pip3 install -U -r requirements.txt

RUN pip3 uninstall dataclasses -y

COPY assets/vnc/image/root/Desktop/. /root/Desktop/
COPY assets/vnc/image/root/Documents/. /root/Documents/

COPY assets/vnc/image/root/icons/. /root/.icons/
COPY assets/vnc/image/usr/bin/. /usr/bin/
COPY assets/vnc/image/opt/ros/noetic/share/rviz/. /opt/ros/noetic/share/rviz/

COPY assets/calibrations/camera_extrinsic/lab.yaml /data/config/camera_extrinsic/
COPY assets/calibrations/camera_intrinsic/lab.yaml /data/config/camera_intrinsic/

RUN rm /root/Desktop/intrinsic_calibration.desktop

ENV PYTHONPATH="${PYTHONPATH}:/jupyter_ws/solution/utils"

# note that this CMD normally gets overwritten
CMD ["dt-launcher-jupyter"]


